name: 'Jira Changelog'
description: 'Generates a changelog message by looking at Jira issue keys ([DEV-123]) in commit messages.'
inputs:
    config:
        description: 'Configuration file for generating the changelog'
        default: '.github/changelog.js'
        required: true
    jira_email:
        description: 'Email address of the user to login with'
        required: true
    jira_token:
        description: 'Auth token of the user to login with'
        required: true
    release:
        description: 'The release name (ie: 3.0.4). This will set the `fixVersions` of all issues found in Jira.'
        required: false
    from:
        description: 'Starting git ref to get range of commits'
        default: "develop"
        required: true
    to:
        description: 'Ending git ref to get range of commits'
        default: "master"
        required: true
outputs:
    changelog:
        description: 'Generated changelog'
runs:
    using: 'node12'
    main: 'index.js'